name: infrastructure-vault-default

services:
  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init
    user: root
    volumes:
      - vault_data:/vault/data
    entrypoint: ["/bin/sh", "-c", "chown -R vault:vault /vault/data && echo 'Permissions fixed'"]
    restart: "no"

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    depends_on:
      vault-init:
        condition: service_completed_successfully
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    volumes:
      - vault_data:/vault/data
      - ./config:/vault/config:ro
    command: server
    networks:
      - infra-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`${VAULT_DOMAIN}`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"

networks:
  infra-public:
    external: true

volumes:
  vault_data:
